export const initialState = [
	{
	  order_id: 2,
	  queryId: 0,
	  comment: '',
	  totalPrice: '58.00',
	  optionDelivery: 'on_site',
	  paymentMethod: 'card',
	  order_date: null,
	  cartItems:
		'[{"id":2,"title":"Coca","price":8,"quantity":2},{"id":1,"title":"Falafel","price":15,"description":"Falafel_description","toppings":[],"quantity":2,"selectedToppings":[]}]',
	  address: '',
	  user_name: 'yair770',
	  user_id: 386212074,
	},
	{
	  order_id: 3,
	  queryId: null,
	  comment: null,
	  totalPrice: null,
	  optionDelivery: null,
	  paymentMethod: null,
	  order_date: null,
	  cartItems: null,
	  address: null,
	  user_name: null,
	  user_id: null,
	},
	{
	  order_id: 4,
	  queryId: null,
	  comment: null,
	  totalPrice: null,
	  optionDelivery: null,
	  paymentMethod: null,
	  order_date: null,
	  cartItems: null,
	  address: null,
	  user_name: null,
	  user_id: null,
	},
	{
	  order_id: 5,
	  queryId: null,
	  comment: null,
	  totalPrice: null,
	  optionDelivery: null,
	  paymentMethod: null,
	  order_date: null,
	  cartItems: null,
	  address: null,
	  user_name: null,
	  user_id: null,
	},
	{
	  order_id: 6,
	  queryId: 0,
	  comment: '',
	  totalPrice: '58.00',
	  optionDelivery: 'on_site',
	  paymentMethod: 'card',
	  order_date: null,
	  cartItems:
		'[{"id":2,"title":"Coca","price":8,"quantity":2},{"id":1,"title":"Falafel","price":15,"description":"Falafel_description","toppings":[],"quantity":2,"selectedToppings":[]}]',
	  address: '',
	  user_name: 'yair770',
	  user_id: 386212074,
	},
	{
	  order_id: 7,
	  queryId: 0,
	  comment: '',
	  totalPrice: '58.00',
	  optionDelivery: 'on_site',
	  paymentMethod: 'card',
	  order_date: null,
	  cartItems:
		'[{"id":2,"title":"Coca","price":8,"quantity":2},{"id":1,"title":"Falafel","price":15,"description":"Falafel_description","toppings":[],"quantity":2,"selectedToppings":[]}]',
	  address: '',
	  user_name: 'yair770',
	  user_id: 386212074,
	},
	{
	  order_id: 8,
	  queryId: 0,
	  comment: '',
	  totalPrice: '123123.00',
	  optionDelivery: 'on_site',
	  paymentMethod: 'card',
	  order_date: null,
	  cartItems:
		'[{"id":1,"title":"Falafel","price":15,"description":"Falafel_description","toppings":[],"quantity":2,"selectedToppings":[]}]',
	  address: '',
	  user_name: 'yair770',
	  user_id: 386212074,
	},
	{
	  order_id: 9,
	  queryId: 0,
	  comment: '',
	  totalPrice: '123123.00',
	  optionDelivery: 'on_site',
	  paymentMethod: 'card',
	  order_date: null,
	  cartItems:
		'[{"id":1,"title":"Falafel","price":15,"description":"Falafel_description","toppings":[],"quantity":2,"selectedToppings":[]}]',
	  address: '',
	  user_name: 'yair770',
	  user_id: 386212074,
	},
	{
	  order_id: 10,
	  queryId: 0,
	  comment: '',
	  totalPrice: '123123.00',
	  optionDelivery: 'on_site',
	  paymentMethod: 'card',
	  order_date: null,
	  cartItems:
		'[{"id":1,"title":"Falafel","price":15,"description":"Falafel_description","toppings":[],"quantity":2,"selectedToppings":[]}]',
	  address: '',
	  user_name: 'yair770',
	  user_id: 386212074,
	},
  ]